<?php
// database/seeders/LivroSeederMelhorado.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Livro;
use Carbon\Carbon;

class LivroSeederMelhorado extends Seeder
{
    public function run()
    {
        $this->command->info('🚀 Criando biblioteca completa...');

        $livros = [
            // FICÇÃO BRASILEIRA
            [
                'titulo' => 'Dom Casmurro',
                'autor' => 'Machado de Assis',
                'isbn' => '9788525406958',
                'editora' => 'Globo Livros',
                'ano_publicacao' => 1899,
                'preco' => 29.90,
                'paginas' => 256,
                'sinopse' => 'Romance clássico da literatura brasileira que narra a história de Bentinho e Capitu, explorando temas como ciúme, traição e a dúvida que corrói o coração humano.',
                'categoria' => 'Literatura Brasileira',
                'estoque' => 15,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => '2ª Edição',
                'genero' => 'ficcao',
                'tags' => ['clássico', 'romance', 'brasileira'],
                'desconto_percentual' => 0,
                'peso' => 300,
                'dimensoes' => '14x21x1.5cm',
                'avaliacao_media' => 4.5,
                'total_avaliacoes' => 1250,
                'total_vendas' => 3500,
            ],
            [
                'titulo' => 'O Cortiço',
                'autor' => 'Aluísio Azevedo',
                'isbn' => '9788520925478',
                'editora' => 'Scipione',
                'ano_publicacao' => 1890,
                'preco' => 24.90,
                'paginas' => 312,
                'sinopse' => 'Obra naturalista que retrata a vida em um cortiço no Rio de Janeiro do século XIX, mostrando as condições sociais da época.',
                'categoria' => 'Literatura Brasileira',
                'estoque' => 8,
                'ativo' => true,
                'destaque' => false,
                'idioma' => 'pt',
                'edicao' => '3ª Edição',
                'genero' => 'ficcao',
                'tags' => ['clássico', 'naturalismo', 'social'],
                'desconto_percentual' => 15.0,
                'peso' => 350,
                'dimensoes' => '14x21x2cm',
                'avaliacao_media' => 4.2,
                'total_avaliacoes' => 890,
                'total_vendas' => 2100,
            ],
            [
                'titulo' => 'Cidade de Deus',
                'autor' => 'Paulo Lins',
                'isbn' => '9788535909827',
                'editora' => 'Companhia das Letras',
                'ano_publicacao' => 1997,
                'preco' => 45.90,
                'paginas' => 551,
                'sinopse' => 'Romance que retrata a violência urbana no Rio de Janeiro através da história da favela Cidade de Deus.',
                'categoria' => 'Literatura Brasileira',
                'estoque' => 12,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => '1ª Edição',
                'genero' => 'ficcao',
                'tags' => ['contemporânea', 'urbana', 'social'],
                'desconto_percentual' => 20.0,
                'peso' => 520,
                'dimensoes' => '14x21x3cm',
                'avaliacao_media' => 4.7,
                'total_avaliacoes' => 2150,
                'total_vendas' => 4200,
            ],

            // FICÇÃO INTERNACIONAL
            [
                'titulo' => '1984',
                'autor' => 'George Orwell',
                'isbn' => '9788535914849',
                'editora' => 'Companhia das Letras',
                'ano_publicacao' => 1949,
                'preco' => 34.90,
                'paginas' => 416,
                'sinopse' => 'Distopia clássica sobre um regime totalitário que controla todos os aspectos da vida humana através da vigilância e manipulação.',
                'categoria' => 'Ficção Científica',
                'estoque' => 22,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Alexandre Hubner',
                'genero' => 'ficcao',
                'tags' => ['distopia', 'clássico', 'futuro'],
                'desconto_percentual' => 10.0,
                'peso' => 380,
                'dimensoes' => '14x21x2.5cm',
                'avaliacao_media' => 4.8,
                'total_avaliacoes' => 5500,
                'total_vendas' => 8900,
            ],
            [
                'titulo' => 'O Pequeno Príncipe',
                'autor' => 'Antoine de Saint-Exupéry',
                'isbn' => '9788535909827',
                'editora' => 'Companhia das Letras',
                'ano_publicacao' => 1943,
                'preco' => 19.90,
                'paginas' => 96,
                'sinopse' => 'Fábula poética sobre amizade, amor e a natureza humana, contada através dos olhos de uma criança.',
                'categoria' => 'Literatura Infantil',
                'estoque' => 30,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Edição Ilustrada',
                'genero' => 'infantil',
                'tags' => ['infantil', 'fábula', 'filosofia'],
                'desconto_percentual' => 25.0,
                'peso' => 180,
                'dimensoes' => '16x23x1cm',
                'avaliacao_media' => 4.9,
                'total_avaliacoes' => 7200,
                'total_vendas' => 12000,
            ],
            [
                'titulo' => 'Cem Anos de Solidão',
                'autor' => 'Gabriel García Márquez',
                'isbn' => '9788501105950',
                'editora' => 'Record',
                'ano_publicacao' => 1967,
                'preco' => 54.90,
                'paginas' => 432,
                'sinopse' => 'Obra-prima do realismo mágico que narra a saga da família Buendía na cidade fictícia de Macondo.',
                'categoria' => 'Literatura Estrangeira',
                'estoque' => 18,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Eric Nepomuceno',
                'genero' => 'ficcao',
                'tags' => ['realismo mágico', 'nobel', 'clássico'],
                'desconto_percentual' => 15.0,
                'peso' => 450,
                'dimensoes' => '14x21x2.8cm',
                'avaliacao_media' => 4.6,
                'total_avaliacoes' => 3200,
                'total_vendas' => 5500,
            ],

            // TECNOLOGIA E PROGRAMAÇÃO
            [
                'titulo' => 'Clean Code: Código Limpo',
                'autor' => 'Robert C. Martin',
                'isbn' => '9788576082675',
                'editora' => 'Alta Books',
                'ano_publicacao' => 2009,
                'preco' => 89.90,
                'paginas' => 464,
                'sinopse' => 'Manual prático sobre como escrever código limpo, legível e manutenível. Técnicas e princípios para desenvolvedores.',
                'categoria' => 'Tecnologia',
                'estoque' => 25,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução Brasileira',
                'genero' => 'tecnologia',
                'tags' => ['programação', 'desenvolvimento', 'boas práticas'],
                'desconto_percentual' => 20.0,
                'peso' => 680,
                'dimensoes' => '17x24x2.5cm',
                'avaliacao_media' => 4.7,
                'total_avaliacoes' => 1850,
                'total_vendas' => 3200,
            ],
            [
                'titulo' => 'Laravel: Desenvolvimento Web com PHP',
                'autor' => 'Alexandre Altair',
                'isbn' => '9788575228142',
                'editora' => 'Casa do Código',
                'ano_publicacao' => 2023,
                'preco' => 79.90,
                'paginas' => 380,
                'sinopse' => 'Guia completo do framework Laravel para desenvolvimento web moderno com PHP. Inclui projetos práticos.',
                'categoria' => 'Tecnologia',
                'estoque' => 15,
                'ativo' => true,
                'destaque' => false,
                'idioma' => 'pt',
                'edicao' => '2ª Edição Atualizada',
                'genero' => 'tecnologia',
                'tags' => ['php', 'laravel', 'web', 'framework'],
                'desconto_percentual' => 25.0,
                'peso' => 550,
                'dimensoes' => '16x23x2cm',
                'avaliacao_media' => 4.4,
                'total_avaliacoes' => 320,
                'total_vendas' => 850,
            ],

            // BIOGRAFIAS E HISTÓRIA
            [
                'titulo' => 'Steve Jobs',
                'autor' => 'Walter Isaacson',
                'isbn' => '9788535914848',
                'editora' => 'Companhia das Letras',
                'ano_publicacao' => 2011,
                'preco' => 69.90,
                'paginas' => 656,
                'sinopse' => 'Biografia oficial de Steve Jobs baseada em mais de quarenta entrevistas com o próprio Jobs e com pessoas próximas.',
                'categoria' => 'Biografia',
                'estoque' => 20,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Berilo Vargas',
                'genero' => 'biografia',
                'tags' => ['biografia', 'tecnologia', 'apple', 'inovação'],
                'desconto_percentual' => 30.0,
                'peso' => 720,
                'dimensoes' => '16x23x3.5cm',
                'avaliacao_media' => 4.6,
                'total_avaliacoes' => 2800,
                'total_vendas' => 4500,
            ],
            [
                'titulo' => 'Sapiens: Uma Breve História da Humanidade',
                'autor' => 'Yuval Noah Harari',
                'isbn' => '9788525431813',
                'editora' => 'L&PM',
                'ano_publicacao' => 2014,
                'preco' => 54.90,
                'paginas' => 464,
                'sinopse' => 'Uma jornada ousada que conecta o passado ao presente e questiona o futuro da humanidade.',
                'categoria' => 'História',
                'estoque' => 35,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Janaína Marcoantonio',
                'genero' => 'historia',
                'tags' => ['história', 'humanidade', 'evolução', 'sociedade'],
                'desconto_percentual' => 20.0,
                'peso' => 520,
                'dimensoes' => '14x21x2.8cm',
                'avaliacao_media' => 4.8,
                'total_avaliacoes' => 6500,
                'total_vendas' => 15000,
            ],

            // FANTASIA E FICÇÃO CIENTÍFICA
            [
                'titulo' => 'O Senhor dos Anéis: A Sociedade do Anel',
                'autor' => 'J.R.R. Tolkien',
                'isbn' => '9788533613577',
                'editora' => 'Martins Fontes',
                'ano_publicacao' => 1954,
                'preco' => 49.90,
                'paginas' => 576,
                'sinopse' => 'Primeiro volume da épica saga que narra a jornada de Frodo para destruir o Um Anel na Terra-média.',
                'categoria' => 'Fantasia',
                'estoque' => 28,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Lenita Esteves',
                'genero' => 'fantasia',
                'tags' => ['fantasia', 'épico', 'aventura', 'clássico'],
                'desconto_percentual' => 15.0,
                'peso' => 650,
                'dimensoes' => '14x21x3.2cm',
                'avaliacao_media' => 4.9,
                'total_avaliacoes' => 8900,
                'total_vendas' => 12500,
            ],
            [
                'titulo' => 'Duna',
                'autor' => 'Frank Herbert',
                'isbn' => '9788576573221',
                'editora' => 'Aleph',
                'ano_publicacao' => 1965,
                'preco' => 59.90,
                'paginas' => 688,
                'sinopse' => 'Épico de ficção científica ambientado no planeta desértico Arrakis, onde a especiaria melange é a substância mais valiosa do universo.',
                'categoria' => 'Ficção Científica',
                'estoque' => 18,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Nova Tradução',
                'genero' => 'ficcao',
                'tags' => ['ficção científica', 'space opera', 'política', 'ecologia'],
                'desconto_percentual' => 25.0,
                'peso' => 780,
                'dimensoes' => '16x23x3.5cm',
                'avaliacao_media' => 4.7,
                'total_avaliacoes' => 4200,
                'total_vendas' => 6800,
            ],

            // ROMANCE E LITERATURA CONTEMPORÂNEA
            [
                'titulo' => 'Me Chame Pelo Seu Nome',
                'autor' => 'André Aciman',
                'isbn' => '9788551004429',
                'editora' => 'Suma',
                'ano_publicacao' => 2007,
                'preco' => 39.90,
                'paginas' => 288,
                'sinopse' => 'Romance sobre o primeiro amor entre Elio e Oliver durante um verão na Riviera Italiana.',
                'categoria' => 'Romance',
                'estoque' => 25,
                'ativo' => true,
                'destaque' => false,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Léa Viveiros de Castro',
                'genero' => 'romance',
                'tags' => ['romance', 'lgbtq+', 'coming-of-age', 'itália'],
                'desconto_percentual' => 20.0,
                'peso' => 320,
                'dimensoes' => '14x21x1.8cm',
                'avaliacao_media' => 4.5,
                'total_avaliacoes' => 3200,
                'total_vendas' => 5500,
            ],
            [
                'titulo' => 'Eleanor Oliphant Está Muito Bem',
                'autor' => 'Gail Honeyman',
                'isbn' => '9788584391318',
                'editora' => 'Globo Livros',
                'ano_publicacao' => 2017,
                'preco' => 44.90,
                'paginas' => 384,
                'sinopse' => 'História tocante sobre Eleanor, uma mulher solitária que aprende sobre amizade, amor e cura.',
                'categoria' => 'Romance',
                'estoque' => 30,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Adriana Lisboa',
                'genero' => 'romance',
                'tags' => ['contemporâneo', 'drama', 'superação', 'amizade'],
                'desconto_percentual' => 15.0,
                'peso' => 420,
                'dimensoes' => '14x21x2.5cm',
                'avaliacao_media' => 4.6,
                'total_avaliacoes' => 5500,
                'total_vendas' => 8200,
            ],

            // AUTOAJUDA E DESENVOLVIMENTO PESSOAL
            [
                'titulo' => 'Hábitos Atômicos',
                'autor' => 'James Clear',
                'isbn' => '9788550804231',
                'editora' => 'Alta Books',
                'ano_publicacao' => 2019,
                'preco' => 49.90,
                'paginas' => 320,
                'sinopse' => 'Método prático para criar bons hábitos e se livrar dos maus hábitos através de pequenas mudanças.',
                'categoria' => 'Autoajuda',
                'estoque' => 40,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Carolina Chaves',
                'genero' => 'autoajuda',
                'tags' => ['hábitos', 'produtividade', 'desenvolvimento', 'psicologia'],
                'desconto_percentual' => 20.0,
                'peso' => 380,
                'dimensoes' => '16x23x2cm',
                'avaliacao_media' => 4.7,
                'total_avaliacoes' => 12500,
                'total_vendas' => 18000,
            ],
            [
                'titulo' => 'O Poder do Agora',
                'autor' => 'Eckhart Tolle',
                'isbn' => '9788575422809',
                'editora' => 'Sextante',
                'ano_publicacao' => 1997,
                'preco' => 39.90,
                'paginas' => 240,
                'sinopse' => 'Guia prático para o desperitamento espiritual e a transformação da consciência.',
                'categoria' => 'Autoajuda',
                'estoque' => 22,
                'ativo' => true,
                'destaque' => false,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Regina Lyra',
                'genero' => 'autoajuda',
                'tags' => ['espiritualidade', 'mindfulness', 'consciência', 'presente'],
                'desconto_percentual' => 10.0,
                'peso' => 280,
                'dimensoes' => '14x21x1.5cm',
                'avaliacao_media' => 4.4,
                'total_avaliacoes' => 8200,
                'total_vendas' => 11500,
            ],

            // LITERATURA JUVENIL
            [
                'titulo' => 'A Culpa é das Estrelas',
                'autor' => 'John Green',
                'isbn' => '9788525054227',
                'editora' => 'Intrínseca',
                'ano_publicacao' => 2012,
                'preco' => 34.90,
                'paginas' => 288,
                'sinopse' => 'Romance sobre Hazel e Augustus, dois adolescentes que se conhecem em um grupo de apoio para crianças com câncer.',
                'categoria' => 'Jovem Adulto',
                'estoque' => 45,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Renata Pettengill',
                'genero' => 'jovem_adulto',
                'tags' => ['young adult', 'romance', 'drama', 'adolescente'],
                'desconto_percentual' => 25.0,
                'peso' => 320,
                'dimensoes' => '14x21x1.8cm',
                'avaliacao_media' => 4.5,
                'total_avaliacoes' => 15500,
                'total_vendas' => 25000,
            ],

            // MISTÉRIO E SUSPENSE
            [
                'titulo' => 'O Silêncio dos Inocentes',
                'autor' => 'Thomas Harris',
                'isbn' => '9788501105851',
                'editora' => 'Record',
                'ano_publicacao' => 1988,
                'preco' => 44.90,
                'paginas' => 352,
                'sinopse' => 'Clarice Starling precisa da ajuda do Dr. Hannibal Lecter para capturar o serial killer Buffalo Bill.',
                'categoria' => 'Suspense',
                'estoque' => 15,
                'ativo' => true,
                'destaque' => false,
                'idioma' => 'pt',
                'edicao' => 'Tradução de Carlos Sussekind',
                'genero' => 'misterio',
                'tags' => ['suspense', 'thriller', 'serial killer', 'psicológico'],
                'desconto_percentual' => 0,
                'peso' => 380,
                'dimensoes' => '14x21x2.2cm',
                'avaliacao_media' => 4.6,
                'total_avaliacoes' => 6200,
                'total_vendas' => 8500,
            ],

            // QUADRINHOS E GRAPHIC NOVELS
            [
                'titulo' => 'Watchmen',
                'autor' => 'Alan Moore',
                'isbn' => '9788575328064',
                'editora' => 'Panini',
                'ano_publicacao' => 1986,
                'preco' => 89.90,
                'paginas' => 416,
                'sinopse' => 'Graphic novel revolucionária que desconstruiu o gênero de super-heróis com uma narrativa complexa e madura.',
                'categoria' => 'Quadrinhos',
                'estoque' => 12,
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Edição Definitiva',
                'genero' => 'quadrinhos',
                'tags' => ['graphic novel', 'super-heróis', 'distopia', 'desconstrução'],
                'desconto_percentual' => 15.0,
                'peso' => 850,
                'dimensoes' => '19x26x2.5cm',
                'avaliacao_media' => 4.8,
                'total_avaliacoes' => 3500,
                'total_vendas' => 4200,
            ],

            // CULINÁRIA
            [
                'titulo' => 'Cozinha Brasileira: Receitas Tradicionais',
                'autor' => 'Ana Luiza Trajano',
                'isbn' => '9788579144234',
                'editora' => 'Senac',
                'ano_publicacao' => 2020,
                'preco' => 79.90,
                'paginas' => 320,
                'sinopse' => 'Coletânea das mais tradicionais receitas da culinária brasileira, de norte a sul do país.',
                'categoria' => 'Culinária',
                'estoque' => 18,
                'ativo' => true,
                'destaque' => false,
                'idioma' => 'pt',
                'edicao' => '1ª Edição',
                'genero' => 'culinaria',
                'tags' => ['culinária', 'receitas', 'brasileiro', 'tradicional'],
                'desconto_percentual' => 20.0,
                'peso' => 680,
                'dimensoes' => '21x28x2cm',
                'avaliacao_media' => 4.3,
                'total_avaliacoes' => 850,
                'total_vendas' => 1200,
            ],

            // ALGUNS COM ESTOQUE BAIXO PARA DEMONSTRAR
            [
                'titulo' => 'Livro Raro - Estoque Baixo',
                'autor' => 'Autor Especial',
                'isbn' => '9780000000001',
                'editora' => 'Editora Especial',
                'ano_publicacao' => 2024,
                'preco' => 199.90,
                'paginas' => 500,
                'sinopse' => 'Este é um livro especial com estoque limitado para demonstrar o sistema de alerta.',
                'categoria' => 'Edição Especial',
                'estoque' => 3, // Estoque baixo
                'ativo' => true,
                'destaque' => true,
                'idioma' => 'pt',
                'edicao' => 'Edição Limitada',
                'genero' => 'ficcao',
                'tags' => ['raro', 'limitado', 'especial'],
                'desconto_percentual' => 0,
                'peso' => 600,
                'dimensoes' => '16x23x3cm',
                'avaliacao_media' => 5.0,
                'total_avaliacoes' => 50,
                'total_vendas' => 150,
            ],

            // ESGOTADO
            [
                'titulo' => 'Livro Esgotado - Demo',
                'autor' => 'Autor Demo',
                'isbn' => '9780000000002',
                'editora' => 'Demo Editora',
                'ano_publicacao' => 2023,
                'preco' => 49.90,
                'paginas' => 200,
                'sinopse' => 'Este livro está temporariamente esgotado para demonstrar o sistema.',
                'categoria' => 'Demo',
                'estoque' => 0, // Esgotado
                'ativo' => true,
                'destaque' => false,
                'idioma' => 'pt',
                'edicao' => '1ª Edição',
                'genero' => 'ficcao',
                'tags' => ['demo', 'esgotado'],
                'desconto_percentual' => 10.0,
                'peso' => 250,
                'dimensoes' => '14x21x1.5cm',
                'avaliacao_media' => 4.0,
                'total_avaliacoes' => 120,
                'total_vendas' => 500,
            ],
        ];

        foreach ($livros as $livroData) {
            // Verificar se o livro já existe (evitar duplicatas)
            $existingLivro = Livro::where('isbn', $livroData['isbn'])->first();
            
            if (!$existingLivro) {
                Livro::create($livroData);
                $this->command->line("✅ Livro '{$livroData['titulo']}' adicionado");
            } else {
                $this->command->line("⚠️  Livro '{$livroData['titulo']}' já existe, pulando...");
            }
        }

        $this->command->info('');
        $this->command->info('🎉 Biblioteca criada com sucesso!');
        $this->command->info('📊 Estatísticas:');
        $this->command->line('📚 Total de livros: ' . Livro::count());
        $this->command->line('⭐ Livros em destaque: ' . Livro::where('destaque', true)->count());
        $this->command->line('🔥 Livros com desconto: ' . Livro::where('desconto_percentual', '>', 0)->count());
        $this->command->line('📦 Total em estoque: ' . Livro::sum('estoque'));
        $this->command->line('⚠️  Estoque baixo: ' . Livro::where('estoque', '>', 0)->where('estoque', '<=', 5)->count());
        $this->command->line('❌ Esgotados: ' . Livro::where('estoque', 0)->count());
        
        $this->command->info('');
        $this->command->info('📂 Categorias disponíveis:');
        $categorias = Livro::select('categoria')
                          ->whereNotNull('categoria')
                          ->groupBy('categoria')
                          ->orderBy('categoria')
                          ->pluck('categoria');
                          
        foreach ($categorias as $categoria) {
            $count = Livro::where('categoria', $categoria)->count();
            $this->command->line("   • {$categoria}: {$count} livros");
        }
    }
}